apiVersion: v1
kind: Service
metadata:
  name: otel-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-agent
  ports:
    - name: rsyslog
      protocol: TCP
      port: 54527
      targetPort: 54527
